export type WineType = 'red' | 'white' | 'rosé';

export type RecommendedWine = {
  id: string;
  initials: string;
  label: string;       // short label rendered on bottle (e.g. "CC")
  appellation: string; // small text on bottle (e.g. "CHIANTI")
  vintage: number;     // year shown on bottle
  name: string;
  country: string;
  region: string;
  coords: [number, number];
  isoNumeric: string;
  priceKrw: number;
  styleHint: string;
  wineType: WineType;
  bottleColor: string;
};

export const STARTING_WINE: RecommendedWine = {
  id: 'bdx-margaux',
  initials: 'CM',
  label: 'CM',
  appellation: 'MARGAUX',
  vintage: 2018,
  name: 'Château Margaux',
  country: '프랑스',
  region: 'Bordeaux',
  coords: [-0.578, 44.838],
  isoNumeric: '250',
  priceKrw: 0,
  styleHint: '당신이 마신 와인',
  wineType: 'red',
  bottleColor: '#5b1424',
};

export const RECOMMENDED_WINES: RecommendedWine[] = [
  {
    id: 'bdx-sup',
    initials: 'BS',
    label: 'BS',
    appellation: 'BORDEAUX',
    vintage: 2020,
    name: 'Bordeaux Supérieur',
    country: '프랑스',
    region: 'Bordeaux',
    coords: [-0.378, 44.638],
    isoNumeric: '250',
    priceKrw: 35000,
    styleHint: '미디엄 바디 보르도',
    wineType: 'red',
    bottleColor: '#6B1421',
  },
  {
    id: 'chianti',
    initials: 'CC',
    label: 'CC',
    appellation: 'CHIANTI',
    vintage: 2021,
    name: 'Chianti Classico',
    country: '이탈리아',
    region: 'Toscana',
    coords: [11.376, 43.469],
    isoNumeric: '380',
    priceKrw: 45000,
    styleHint: '체리·허브, 부드러운 탄닌',
    wineType: 'red',
    bottleColor: '#8B1A2A',
  },
  {
    id: 'valpo',
    initials: 'VP',
    label: 'VP',
    appellation: 'VALPO',
    vintage: 2022,
    name: 'Valpolicella',
    country: '이탈리아',
    region: 'Veneto',
    coords: [10.992, 45.439],
    isoNumeric: '380',
    priceKrw: 38000,
    styleHint: '가벼운 베리, 산미',
    wineType: 'red',
    bottleColor: '#A8233A',
  },
  {
    id: 'rioja',
    initials: 'RJ',
    label: 'RJ',
    appellation: 'RIOJA',
    vintage: 2019,
    name: 'Rioja Crianza',
    country: '스페인',
    region: 'Rioja',
    coords: [-2.45, 42.46],
    isoNumeric: '724',
    priceKrw: 35000,
    styleHint: '템프라니요 입문',
    wineType: 'red',
    bottleColor: '#6B1421',
  },
  {
    id: 'casillero',
    initials: 'CD',
    label: 'CD',
    appellation: 'CHILE',
    vintage: 2022,
    name: 'Casillero del Diablo',
    country: '칠레',
    region: 'Central Valley',
    coords: [-70.66, -33.45],
    isoNumeric: '152',
    priceKrw: 22000,
    styleHint: '편의점 가성비 입문',
    wineType: 'red',
    bottleColor: '#5b1424',
  },
  {
    id: 'mendoza',
    initials: 'MM',
    label: 'MM',
    appellation: 'MENDOZA',
    vintage: 2020,
    name: 'Mendoza Malbec',
    country: '아르헨티나',
    region: 'Mendoza',
    coords: [-68.85, -32.89],
    isoNumeric: '032',
    priceKrw: 32000,
    styleHint: '진한 과실, 부드러움',
    wineType: 'red',
    bottleColor: '#4a1226',
  },
  {
    id: 'cloudy',
    initials: 'CB',
    label: 'CB',
    appellation: 'MARLBOR',
    vintage: 2023,
    name: 'Cloudy Bay SB',
    country: '뉴질랜드',
    region: 'Marlborough',
    coords: [173.95, -41.52],
    isoNumeric: '554',
    priceKrw: 65000,
    styleHint: '상쾌한 화이트 입문',
    wineType: 'white',
    bottleColor: '#7a5c10',
  },
  {
    id: 'jacobs',
    initials: 'JC',
    label: 'JC',
    appellation: 'SHIRAZ',
    vintage: 2021,
    name: "Jacob's Creek Shiraz",
    country: '호주',
    region: 'South Australia',
    coords: [138.6, -34.93],
    isoNumeric: '036',
    priceKrw: 28000,
    styleHint: '풀바디 입문',
    wineType: 'red',
    bottleColor: '#7c1c33',
  },
  {
    id: 'pinot-or',
    initials: 'PO',
    label: 'PO',
    appellation: 'OREGON',
    vintage: 2021,
    name: 'Oregon Pinot Noir',
    country: '미국',
    region: 'Willamette',
    coords: [-123.06, 45.30],
    isoNumeric: '840',
    priceKrw: 55000,
    styleHint: '가벼운 피노 누아 입문',
    wineType: 'red',
    bottleColor: '#8B1A2A',
  },
];

export const formatKrw = (krw: number) => `₩${krw.toLocaleString('ko-KR')}`;
